MAX_ROBOTS = 5
MAX_WIDTH = 200
MAX_HEIGHT = 200
MAX_GENERATE_ATTEMPTS = 12

DEFAULT_WALL_DENSITY_MIN = 0.02
DEFAULT_WALL_DENSITY_MAX = 0.06
DEFAULT_WALL_RANGE = (DEFAULT_WALL_DENSITY_MIN, DEFAULT_WALL_DENSITY_MAX)

DEFAULT_TASK_COUNT_MIN = 12
DEFAULT_TASK_COUNT_MAX = 24
DEFAULT_TASK_RANGE = (DEFAULT_TASK_COUNT_MIN, DEFAULT_TASK_COUNT_MAX)

DEFAULT_MOVING_COUNT_MIN = 1
DEFAULT_MOVING_COUNT_MAX = 6
DEFAULT_MOVING_RANGE = (DEFAULT_MOVING_COUNT_MIN, DEFAULT_MOVING_COUNT_MAX)

DEFAULT_ROBOT_COUNT_MIN = 2
DEFAULT_ROBOT_COUNT_MAX = 4
DEFAULT_ROBOT_RANGE = (DEFAULT_ROBOT_COUNT_MIN, DEFAULT_ROBOT_COUNT_MAX)

FORKLIFT_PATH_MIN = 100
FORKLIFT_PATH_MAX = 100

ROBOT_COLORS = ["#0b69ff", "#ff5f55", "#2dbf88", "#e2a72e", "#7b5fff"]

WALL_DENSITY_MIN = 0.02
WALL_DENSITY_MAX = 0.45

CSP_MAX_OFFSET = 20
CSP_HORIZON_BUFFER = 10

GA_DEFAULT_POPULATION = 40
GA_DEFAULT_GENERATIONS = 80
GA_DEFAULT_MUTATION_RATE = 0.3
GA_TOURNAMENT_SIZE = 3

LOCAL_SEARCH_DEFAULT_ITERATIONS = 2000
LOCAL_SEARCH_SIMULATED_ANNEALING_PROB = 0.05

REPLAN_HORIZON = 40
